[package]
name = "perception"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
ocrs.workspace = true
ppocrv6-tiny-preflight = { package = "naky-ocr-runtime", path = "../ppocrv6-tiny-runtime" }
rten.workspace = true
rten-imageproc.workspace = true
rten-tensor.workspace = true
screenevents = { path = "../screenevents" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true

[lints]
workspace = true
